export PYTHONPATH=$PYTHONPATH:`pwd`/..
python3 q_advancedaxesdemo.py
python3 q_axis-tags.py
python3 q_barchartdemo.py
python3 q_colormapdemo.py
python3 q_datedemo.py
python3 q_financialdemo.py
python3 q_interactionexample.py
python3 q_itemdemo.py
python3 q_linestyledemo.py
python3 q_logarithmicdemo.py
python3 q_multiaxisdemo.py
python3 q_parametriccurvesdemo.py
python3 q_quadraticdemo.py
python3 q_realtimedatademo.py
python3 q_scatterpixmapdemo.py
python3 q_scatterstyledemo.py
python3 q_scrollbar-axis-range-control.py
python3 q_simpledemo.py
python3 q_simpleitemdemo.py
python3 q_sincscatterdemo.py
python3 q_statisticaldemo.py
python3 q_styleddemo.py
python3 q_texturebrushdemo.py
