set PYTHONPATH=%PYTHONPATH%;%cd%\..
python q_advancedaxesdemo.py
python q_axis-tags.py
python q_barchartdemo.py
python q_colormapdemo.py
python q_datedemo.py
python q_financialdemo.py
python q_interactionexample.py
python q_itemdemo.py
python q_linestyledemo.py
python q_logarithmicdemo.py
python q_multiaxisdemo.py
python q_parametriccurvesdemo.py
python q_quadraticdemo.py
python q_realtimedatademo.py
python q_scatterpixmapdemo.py
python q_scatterstyledemo.py
python q_scrollbar-axis-range-control.py
python q_simpledemo.py
python q_simpleitemdemo.py
python q_sincscatterdemo.py
python q_statisticaldemo.py
python q_styleddemo.py
python q_texturebrushdemo.py
