name: Docker Manylinux Wheels

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  #release:
  #  types: [published, created, edited]
  
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build manually'     
        required: false
        default: false  

jobs:
  create_linux_wheels:
    runs-on: ubuntu-latest
    container: 
      image: lyxhub/manylinux2014_x86_64_qt
      #options: -v ${{ github.workspace }}:/io    
      volumes: 
        - ${{ github.workspace }}/..:/io    
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check environment
      run: |
        echo "host"
        hostname
        echo "whoami"
        whoami
        echo "pwd"
        pwd
        echo "home"
        ls -l /home
        echo "PWD"
        ls -l
        echo "/"
        ls -l /
        echo "/opt"
        ls -l /opt
        echo "/io"
        ls -l /io
        echo "/__w"
        ls -l /__w
        echo "/__w/Pyside-QCP"
        ls -l /__w/Pyside-QCP
        echo "WS=" ${{ github.workspace }}
        
        
    - name: Make wheels
      working-directory: ${{github.workspace}}
      run: |
        pwd
        chmod u+x ./build-wheels.sh
        ./build-wheels.sh  
        
    - uses: actions/upload-artifact@v3
      with:
        name: wheelhouse_linux_2_1_5
        path: ${{github.workspace}}/wheelhouse/*     



    
    
