name: Docker Manylinux QCP Wheels

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build manually'     
        required: false
        default: false  

jobs:
  install_stuff:
    runs-on: ubuntu-latest
    container: 
      image: lyxhub/manylinux2014_x86_64_qt
      #options: -v ${{ github.workspace }}:/io    
      volumes: 
        - ${{ github.workspace }}:/io    
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Bla
      run: |
        hostname
        pwd
        echo "PWD"
        ls -l
        echo "/"
        ls -l /
        echo "/opt"
        ls -l /opt
        echo "/io"
        ls -l /io
        echo "/__w"
        ls -l /__w
        echo "/__w/Pyside-QCP"
        ls -l /__w/Pyside-QCP
        echo "WS=" ${{ github.workspace }}
        ls -l ${{ github.workspace }}
        
    - name: Make wheels
      run: |
        cd /io
        #git clone https://github.com/SBGit-2019/Pyside-QCP.git
        ${{ github.workspace }}/Pyside-QCP/build-wheels.sh  
        ls -l /io/
        ls -l /io/Pyside-QCP
        ls -l /io/Pyside-QCP/wheelhouse/
        
    - uses: actions/upload-artifact@v3
      with:
        name: wheelhouse
        path: ${{github.workspace}}/wheelhouse/*     



    
    